// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 838ad1c8e9877f026be331e51e87cd74bec26512abf8f2d63d1509aa0b5d3de2


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "custom-theme";

export const themeNames: ThemeName[] = ["custom-theme"];

export type KcEnvName = "HOME_URL";

export const kcEnvNames: KcEnvName[] = ["HOME_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "HOME_URL": "https://sandbox.purgatoryforcookies.com"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
