services:
  db:
    image: postgres:17.4
    ports:
      - 5432:5432
    env_file: '.env'
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_USER}
      - PG_DB=${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-U', 'postgres', '-d', 'db_prod']
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 3s
  backend:
    image: sandbox
    build:
      context: .
    env_file: '.env'
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - KEYCLOAK_TOKEN=${KEYCLOAK_TOKEN}
      - KEYCLOAK_AUTH=${KEYCLOAK_AUTH}
      - KEYCLOAK_USERINFO=${KEYCLOAK_USERINFO}
      - KEYCLOAK_LOGOUT=${KEYCLOAK_LOGOUT}
      - KEYCLOAK_CALLBACK_URL=${KEYCLOAK_CALLBACK_URL}
      - DATABASE_URL=${DATABASE_URL}
