services:
  db:
    image: postgres:17.4
    env_file: '.env'
    ports:
      - 5432:5432
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_USER}
      - PG_DB=${POSTGRES_DB}
  backend:
    image: sandbox
    container_name: backend
    build:
      context: .
    env_file: '.env'
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - AUTH_AUDIENCE=${AUTH_AUDIENCE}
      - DATABASE_URL=${DATABASE_URL}
