services:
  db:
    image: postgres:17.4
    env_file: '.env'
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_USER}
      - PG_DB=${POSTGRES_DB}
  # backend:
  #   image: sandbox
  #   container_name: backend
  #   build:
  #     context: .
  #   env_file: '.env'
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_PASSWORD}
  #     - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
  #     - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
  #     - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
  #     - KEYCLOAK_TOKEN=${KEYCLOAK_TOKEN}
  #     - KEYCLOAK_AUTH=${KEYCLOAK_AUTH}
  #     - KEYCLOAK_USERINFO=${KEYCLOAK_USERINFO}
  #     - KEYCLOAK_LOGOUT=${KEYCLOAK_LOGOUT}
  #     - KEYCLOAK_CALLBACK_URL=${KEYCLOAK_CALLBACK_URL}
  #     - DATABASE_URL=${DATABASE_URL}
